### PR TITLE
Develop merge to Main

### PR DESCRIPTION
**Pull request by skywalker0823**
Completed most of the task's demand.

楊子軒, Pikxl_

Link below:
http://52.33.215.189:3000/
http://52.33.215.189:3000/attraction/10

To do :
The JS and CSS code is a bit messy.
Adding Error page when connects to a null page.

### CODE REVIEW

**Comment by skywalker0823** [comment]
Error page completed, now checking CSS adaption in some specific conditions and adjusting according to the Figma's design.

**Comment by skywalker0823** [comment]
Will do and still improving:
Keep adjusted CSS and delete unused code.
The loading of jpg sometimes shown slow, expected but should find something to deal with this.
Try merging JS codes, and planning thoughts of MVC design pattern.

**Comment by cwpeng** [comment]
1. Margins between circles of slide should be closer.
2. Separating line of top part and bottom part should be only 1 px height.

**Comment by skywalker0823** [comment]
The dots should look fine now.

**Comment by cwpeng** [comment]
From my view, there is still 2px height of your separating line. Try to just set border-top to 1px.

**Comment by skywalker0823** [comment]
Just set the border-top to 1px, should be fine. I hope.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
